

try {
    throw 5
    print ('success')
} catch e {
    print ('caught')
    throw 3
}
